package qris

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// fixtures mirrors testdata/fixtures.json generated by the reference TypeScript
// implementation (see tools/generate_fixtures.mjs).
type fixtures struct {
	Samples []struct {
		Input  string `json:"input"`
		Parsed struct {
			Version             string `json:"version"`
			Method              string `json:"method"`
			MerchantAccountInfo []struct {
				Tag              string `json:"tag"`
				GloballyUniqueID string `json:"globallyUniqueId"`
				MerchantID       string `json:"merchantId"`
				MerchantCriteria string `json:"merchantCriteria"`
			} `json:"merchantAccountInfo"`
			MerchantCategoryCode string `json:"merchantCategoryCode"`
			Currency             string `json:"currency"`
			Amount               string `json:"amount"`
			TipIndicator         string `json:"tipIndicator"`
			TipFixed             string `json:"tipFixed"`
			TipPercentage        string `json:"tipPercentage"`
			CountryCode          string `json:"countryCode"`
			MerchantName         string `json:"merchantName"`
			MerchantCity         string `json:"merchantCity"`
			PostalCode           string `json:"postalCode"`
			CRC                  string `json:"crc"`
			RawTags              []struct {
				Tag    string `json:"tag"`
				Name   string `json:"name"`
				Length int    `json:"length"`
				Value  string `json:"value"`
			} `json:"rawTags"`
		} `json:"parsed"`
		Validation  ValidationFixture `json:"validation"`
		Conversions struct {
			NoFee      string `json:"noFee"`
			FixedFee   string `json:"fixedFee"`
			PercentFee string `json:"percentFee"`
			Penny      string `json:"penny"`
		} `json:"conversions"`
	} `json:"samples"`
	InvalidSamples []struct {
		Input      string            `json:"input"`
		Validation ValidationFixture `json:"validation"`
	} `json:"invalidSamples"`
}

type ValidationFixture struct {
	Valid  bool     `json:"valid"`
	Errors []string `json:"errors"`
}

func loadFixtures(t *testing.T) *fixtures {
	t.Helper()
	b, err := os.ReadFile("testdata/fixtures.json")
	if err != nil {
		t.Fatalf("read fixtures: %v", err)
	}
	var f fixtures
	if err := json.Unmarshal(b, &f); err != nil {
		t.Fatalf("unmarshal fixtures: %v", err)
	}
	return &f
}

func TestCRC16(t *testing.T) {
	f := loadFixtures(t)
	for _, s := range f.Samples {
		body := s.Input[:len(s.Input)-4]
		got := CalculateCRC16(body)
		want := s.Parsed.CRC
		if got != want {
			t.Errorf("CalculateCRC16(%q) = %s, want %s", body, got, want)
		}
	}
}

func TestParseParity(t *testing.T) {
	f := loadFixtures(t)
	for _, s := range f.Samples {
		got := Parse(s.Input)

		wantMethod := Method(s.Parsed.Method)
		if got.Method != wantMethod {
			t.Errorf("method = %q, want %q", got.Method, wantMethod)
		}
		if got.Version != s.Parsed.Version {
			t.Errorf("version = %q, want %q", got.Version, s.Parsed.Version)
		}
		if got.MerchantCategoryCode != s.Parsed.MerchantCategoryCode {
			t.Errorf("mcc = %q, want %q", got.MerchantCategoryCode, s.Parsed.MerchantCategoryCode)
		}
		if got.Currency != s.Parsed.Currency {
			t.Errorf("currency = %q, want %q", got.Currency, s.Parsed.Currency)
		}
		if got.Amount != s.Parsed.Amount {
			t.Errorf("amount = %q, want %q", got.Amount, s.Parsed.Amount)
		}
		if string(got.TipIndicator) != s.Parsed.TipIndicator {
			t.Errorf("tipIndicator = %q, want %q", got.TipIndicator, s.Parsed.TipIndicator)
		}
		if got.TipFixed != s.Parsed.TipFixed {
			t.Errorf("tipFixed = %q, want %q", got.TipFixed, s.Parsed.TipFixed)
		}
		if got.TipPercentage != s.Parsed.TipPercentage {
			t.Errorf("tipPercentage = %q, want %q", got.TipPercentage, s.Parsed.TipPercentage)
		}
		if got.CountryCode != s.Parsed.CountryCode {
			t.Errorf("countryCode = %q, want %q", got.CountryCode, s.Parsed.CountryCode)
		}
		if got.MerchantName != s.Parsed.MerchantName {
			t.Errorf("merchantName = %q, want %q", got.MerchantName, s.Parsed.MerchantName)
		}
		if got.MerchantCity != s.Parsed.MerchantCity {
			t.Errorf("merchantCity = %q, want %q", got.MerchantCity, s.Parsed.MerchantCity)
		}
		if got.PostalCode != s.Parsed.PostalCode {
			t.Errorf("postalCode = %q, want %q", got.PostalCode, s.Parsed.PostalCode)
		}
		if got.CRC != s.Parsed.CRC {
			t.Errorf("crc = %q, want %q", got.CRC, s.Parsed.CRC)
		}

		if len(got.MerchantAccountInfo) != len(s.Parsed.MerchantAccountInfo) {
			t.Fatalf("merchantAccountInfo len = %d, want %d", len(got.MerchantAccountInfo), len(s.Parsed.MerchantAccountInfo))
		}
		for i, want := range s.Parsed.MerchantAccountInfo {
			g := got.MerchantAccountInfo[i]
			if g.Tag != want.Tag || g.GloballyUniqueID != want.GloballyUniqueID ||
				g.MerchantID != want.MerchantID || g.MerchantCriteria != want.MerchantCriteria {
				t.Errorf("merchantAccountInfo[%d] = %+v, want %+v", i, g, want)
			}
		}

		// Deep-compare raw TLV tree: normalize children presence.
		// Keys tested via rawTags (flat, includes names/lengths).
		if len(got.Raw) != len(s.Parsed.RawTags) {
			t.Fatalf("raw len = %d, want %d", len(got.Raw), len(s.Parsed.RawTags))
		}
		for i, want := range s.Parsed.RawTags {
			g := got.Raw[i]
			if g.Tag != want.Tag || g.Name != want.Name || g.Length != want.Length || g.Value != want.Value {
				t.Errorf("raw[%d] = {%s %s %d %q}, want {%s %s %d %q}",
					i, g.Tag, g.Name, g.Length, g.Value, want.Tag, want.Name, want.Length, want.Value)
			}
		}
	}
}

func TestParseTLVNested(t *testing.T) {
	// DANA sample carries a real nested merchant-account block under tag 26.
	els := ParseTLV("00020101021126570011ID.DANA.WWW01189360091502123890310id.co.dana.www01021114220015071700000000012280028ID.CO.DANA.WWW01189360091502123890352040000940836002ID5204581253033605802ID5908WARUNG-X6008JAKARTA6304E010")
	if len(els) == 0 {
		t.Fatal("no elements parsed")
	}
	var found bool
	for _, e := range els {
		if e.Tag == "26" && len(e.Children) > 0 {
			found = true
			if e.Children[0].Tag != "00" {
				t.Errorf("first child of 26 = %s, want 00", e.Children[0].Tag)
			}
		}
	}
	if !found {
		t.Error("expected nested children under tag 26")
	}
}

func TestConvertParity(t *testing.T) {
	f := loadFixtures(t)
	for _, s := range f.Samples {
		noFee := Convert(s.Input, ConvertOptions{Amount: "25000"})
		if noFee != s.Conversions.NoFee {
			t.Errorf("noFee convert mismatch:\n got  %s\n want %s", noFee, s.Conversions.NoFee)
		}
		fixed := Convert(s.Input, ConvertOptions{Amount: "25000", Fee: &ConvertFee{Type: FeeFixed, Value: 1000}})
		if fixed != s.Conversions.FixedFee {
			t.Errorf("fixedFee convert mismatch:\n got  %s\n want %s", fixed, s.Conversions.FixedFee)
		}
		pct := Convert(s.Input, ConvertOptions{Amount: "25000", Fee: &ConvertFee{Type: FeePercentage, Value: 2.5}})
		if pct != s.Conversions.PercentFee {
			t.Errorf("percentFee convert mismatch:\n got  %s\n want %s", pct, s.Conversions.PercentFee)
		}
		penny := Convert(s.Input, ConvertOptions{Amount: "12345", Fee: &ConvertFee{Type: FeePercentage, Value: 0.5}})
		if penny != s.Conversions.Penny {
			t.Errorf("penny convert mismatch:\n got  %s\n want %s", penny, s.Conversions.Penny)
		}
		// Converted results must always carry a valid CRC.
		data := Parse(penny)
		if data.CRC == "" {
			t.Error("converted string has no CRC tag")
		}
	}
}

func TestValidateParity(t *testing.T) {
	f := loadFixtures(t)
	for _, s := range f.Samples {
		got := Validate(s.Input)
		want := ValidationResult{Valid: s.Validation.Valid, Errors: s.Validation.Errors}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("Validate(%q) = %+v, want %+v", s.Input, got, want)
		}
	}
	for _, s := range f.InvalidSamples {
		got := Validate(s.Input)
		want := ValidationResult{Valid: s.Validation.Valid, Errors: s.Validation.Errors}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("Validate(%q) = %+v, want %+v", s.Input, got, want)
		}
	}
}
